# Laravel + Inertia (SSR opcional) — Dokploy + Nixpacks

[phases.setup]
# Pacotes Nix corretos. Sem placeholder.
nixPkgs = [
  "nginx",
  "php83",
  "php83Packages.composer",
  "php83Extensions.curl",
  "php83Extensions.mbstring",
  "php83Extensions.pdo_mysql",
  "php83Extensions.opcache",
  "nodejs_20",
  "python3Packages.supervisor"
]

[phases.build]
cmds = [
  # supervisor/nginx/php-fpm configs
  "mkdir -p /etc/supervisor/conf.d/",
  "cp /assets/worker-*.conf /etc/supervisor/conf.d/",
  "cp /assets/supervisord.conf /etc/supervisord.conf",
  "chmod +x /assets/start.sh",

  # deps PHP/Node
  "composer install --no-dev --prefer-dist --optimize-autoloader --no-interaction",
  "php artisan config:cache || true",
  "php artisan route:cache || true",
  "php artisan view:cache || true",
  "npm ci --no-audit --no-fund",
  "npm run build"
]

[start]
cmd = "/assets/start.sh"

[staticAssets]
"start.sh" = '''
#!/bin/bash
# Gera nginx.conf a partir do template
node /assets/scripts/prestart.mjs /assets/nginx.template.conf /etc/nginx.conf 2>/dev/null || cp /assets/nginx.template.conf /etc/nginx.conf
# Inicia supervisor (nginx + php-fpm + queue + SSR opcional)
exec supervisord -c /etc/supervisord.conf -n
'''

"supervisord.conf" = '''
[unix_http_server]
file=/assets/supervisor.sock
[supervisord]
logfile=/var/log/supervisord.log
pidfile=/assets/supervisord.pid
nodaemon=true
[include]
files = /etc/supervisor/conf.d/*.conf
'''

"worker-nginx.conf" = '''
[program:worker-nginx]
command=nginx -c /etc/nginx.conf
autostart=true
autorestart=true
stdout_logfile=/var/log/worker-nginx.log
stderr_logfile=/var/log/worker-nginx.log
'''

"worker-phpfpm.conf" = '''
[program:worker-phpfpm]
; php-fpm do php83
command=php-fpm -F
autostart=true
autorestart=true
stdout_logfile=/var/log/worker-phpfpm.log
stderr_logfile=/var/log/worker-phpfpm.log
'''

"worker-laravel.conf" = '''
[program:worker-laravel]
command=bash -c 'exec php /app/artisan queue:work --sleep=3 --tries=3 --max-time=3600'
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
numprocs=2
stdout_logfile=/var/log/worker-laravel.log
stderr_logfile=/var/log/worker-laravel.log
'''

"worker-inertia-ssr.conf" = '''
[program:inertia-ssr]
command=bash -c 'exec php /app/artisan inertia:start-ssr'
autostart=false
autorestart=true
stdout_logfile=/var/log/worker-inertia-ssr.log
stderr_logfile=/var/log/worker-inertia-ssr.log
'''

"nginx.template.conf" = '''
user www-data www-data;
worker_processes 2;
daemon off;
events { worker_connections  1024; }
http {
  include    $!{nginx}/conf/mime.types;
  index      index.php;
  default_type application/octet-stream;
  access_log /var/log/nginx-access.log;
  error_log  /var/log/nginx-error.log;
  sendfile on;

  server {
    listen 80;
    listen [::]:80;
    server_name _;

    root /app/public;

    add_header X-Content-Type-Options "nosniff";
    client_max_body_size 64M;
    index index.php;
    charset utf-8;

    location / {
      try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
      fastcgi_pass 127.0.0.1:9000;
      fastcgi_buffer_size 8k; # Inertia
      fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
      include $!{nginx}/conf/fastcgi_params;
      include $!{nginx}/conf/fastcgi.conf;
    }

    location ~ /\.(?!well-known).* { deny all; }
  }
}
'''