# nixpacks.toml — Laravel + Inertia (com SSR opcional) no Dokploy

[phases.setup]
# Adiciona supervisor (usando Python) e garante Node para o Vite
nixPkgs = ["...", "python311Packages.supervisor", "nodejs_20"]

[phases.build]
# Ajusta supervisord/nginx/php-fpm e compila assets
cmds = [
  "mkdir -p /etc/supervisor/conf.d/",
  "cp /assets/worker-*.conf /etc/supervisor/conf.d/",
  "cp /assets/supervisord.conf /etc/supervisord.conf",
  "chmod +x /assets/start.sh",
  # Dependências PHP e Node
  "composer install --no-dev --prefer-dist --optimize-autoloader --no-interaction",
  "php artisan route:cache || true",
  "php artisan config:cache || true",
  "php artisan view:cache || true",
  "npm ci --no-audit --no-fund",
  "npm run build"
]

[start]
cmd = "/assets/start.sh"

[staticAssets]
# Script de start: transforma o template do nginx e inicia supervisor
"start.sh" = '''
#!/bin/bash
# Gera nginx.conf a partir do template
node /assets/scripts/prestart.mjs /assets/nginx.template.conf /etc/nginx.conf
# Inicia supervisor (nginx + php-fpm + queue + SSR opcional)
exec supervisord -c /etc/supervisord.conf -n
'''

# Configurações do supervisor
"supervisord.conf" = '''
[unix_http_server]
file=/assets/supervisor.sock
[supervisord]
logfile=/var/log/supervisord.log
pidfile=/assets/supervisord.pid
nodaemon=true
[include]
files = /etc/supervisor/conf.d/*.conf
'''

# Nginx
"worker-nginx.conf" = '''
[program:worker-nginx]
command=nginx -c /etc/nginx.conf
autostart=true
autorestart=true
stdout_logfile=/var/log/worker-nginx.log
stderr_logfile=/var/log/worker-nginx.log
'''

# PHP-FPM
"worker-phpfpm.conf" = '''
[program:worker-phpfpm]
command=php-fpm -y /assets/php-fpm.conf -F
autostart=true
autorestart=true
stdout_logfile=/var/log/worker-phpfpm.log
stderr_logfile=/var/log/worker-phpfpm.log
'''

# Queue worker (ajuste numprocs conforme recurso)
"worker-laravel.conf" = '''
[program:worker-laravel]
command=bash -c 'exec php /app/artisan queue:work --sleep=3 --tries=3 --max-time=3600'
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
numprocs=2
stdout_logfile=/var/log/worker-laravel.log
stderr_logfile=/var/log/worker-laravel.log
'''

# SSR do Inertia (OPCIONAL) — habilite se usar SSR
"worker-inertia-ssr.conf" = '''
[program:inertia-ssr]
command=bash -c 'exec php /app/artisan inertia:start-ssr'
autostart=true
autorestart=true
stdout_logfile=/var/log/worker-inertia-ssr.log
stderr_logfile=/var/log/worker-inertia-ssr.log
'''

# PHP-FPM config
"php-fpm.conf" = '''
[www]
listen = 127.0.0.1:9000
user = www-data
group = www-data
pm = dynamic
pm.max_children = 50
pm.min_spare_servers = 4
pm.max_spare_servers = 32
pm.start_servers = 8
clear_env = no
php_admin_value[post_max_size] = 64M
php_admin_value[upload_max_filesize] = 64M
'''

# Template do Nginx com ajuste para Inertia (buffer) e fallback Laravel
"nginx.template.conf" = '''
user www-data www-data;
worker_processes 2;
daemon off;
events { worker_connections  1024; }
http {
  include    $!{nginx}/conf/mime.types;
  index      index.php;
  default_type application/octet-stream;
  access_log /var/log/nginx-access.log;
  error_log  /var/log/nginx-error.log;
  sendfile on;

  server {
    # Dokploy vai rotear para a porta 80 deste container
    listen 80;
    listen [::]:80;
    server_name _;

    $if(NIXPACKS_PHP_ROOT_DIR) ( root ${NIXPACKS_PHP_ROOT_DIR}; ) else ( root /app/public; )

    add_header X-Content-Type-Options "nosniff";
    client_max_body_size 64M;
    index index.php;
    charset utf-8;

    location / {
      try_files $uri $uri/ /index.php?$query_string;
    }

    # Inertia: buffer maior para respostas
    location ~ \.php$ {
      fastcgi_pass 127.0.0.1:9000;
      fastcgi_buffer_size 8k;
      fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
      include $!{nginx}/conf/fastcgi_params;
      include $!{nginx}/conf/fastcgi.conf;
    }

    location ~ /\.(?!well-known).* { deny all; }
  }
}
'''